# Generated by Django 5.1.7 on 2025-03-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
